---
title: "p8105_hw6_jd3924"
author: "Jiahe Deng"
date: "2022-12-01"
output: github_document
---

```{r}
library(tidyverse)
library(dplyr)
library(readr)
library(mgcv)
library(modelr)
```
Question2
```{r}
homicides_data = 
  read_csv("homicide-data.csv") %>%
  mutate(
    city_state = str_c(city,state, sep = ","),
    victim_age = as.numeric(victim_age),
    resolved = ifelse(disposition %in% c("Closed without arrest","Open/No arrest"), "unsolved","solved")) %>%
  filter(victim_race %in% c("White", "Black"),
         city_state != "Tulsa,AL")

homicides_data
```
```{r}
baltimore_df = 
  homicides_data %>%
  filter(city_state == "Baltimore,MD")
baltimore_df
```
```{r}
fit_logistic = 
  baltimore_df %>% 
  mutate(resolved = as.factor(resolved)) %>%
  glm(resolved ~ victim_age + victim_race + victim_sex, data = ., family = binomial())

fit_logistic %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate),
         lower = exp(estimate - 1.96 * std.error),
         upper = exp(estimate + 1.96 * std.error)) %>%
  knitr::kable(digits = 3)
```


```{r}
glm_cities = 
  homicides_data %>%
  nest(data = -city_state) %>%
  mutate(
    models = map(data, ~glm(as.factor(resolved) ~ victim_age + victim_race + victim_sex, data = .x, family = binomial())),
  results = map(models, broom::tidy)) %>% 
  select(-data, -models) %>% 
  unnest(results)

glm_cities = 
  glm_cities %>% 
  mutate(OR = exp(estimate),
         lower = exp(estimate - 1.96 * std.error),
         upper = exp(estimate + 1.96 * std.error))
glm_cities
```

```{r}
male_vs_female = 
  glm_cities %>%
  filter(term == "victim_sexMale") %>%
  mutate(city_state = fct_reorder(city_state, OR)) %>%
  ggplot(aes(x = city_state, y = OR)) +
  geom_point() + 
  geom_errorbar(aes(ymin = lower, ymax = upper)) + 
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
male_vs_female
```
Question3
```{r}
birthweight = 
  read_csv("birthweight.csv") %>%
  janitor::clean_names()
```


